language: php
php:
    - '7.0'
    - '7.1'
    - '7.2'
services:
    - postgresql
install:
    - composer install
notifications:
  slack:
    rooms:
      - secure: pZ3M9ar/HRfxwbpdhCUSH3pk760zIQvj/xF9l2JON0e3iuxewH9MBpf4YPMtUHAlsAKxfQZL4uszyqr7pAENi1H7pbvRzAggNW2hMhc616KGR1M99zPGzucQZmaSLTik128vCWKfjvGEAXiRMMizyfYADzcY4hBqj8nfE23G7SFFh4WV4Ujj3IxeJUvSRRufSq38hvGB+Hkrh+K+BbBtCjwxcK6wyoLE7ymPlxLrlL1pZdLSqkOkVv8w+QCrqZ3bqJrc0x3n4QaK9f/VHWwQR+ATyLR+2bwoYwsoSLexvmu8Ler1I5Vp2ZR4sDr5h9ui6Fk3njkAhXnrx7eiY2Yq+t77Cc4mTlaH5inqvtCyYl34H1L10MJst54167qjLCWDZsQLp6UwniAZlldL9tP3fNT5dN2dXqMbKO9L0RwegmIlOsMTo8DdHekxAYudlRqPBy7B6tPwYfoOlp6aw8gq28+0C6k5xxRnQFZ9HkVTGcIAhHtXfjsNnIjRbHwdyHXQZPOQvw58mIylqe6j5eEUdaOPR70Z6YWgD7N4F/XGyAlPLMhoLLU3LhUnSKtG2W8bYQzMO7LJrCWcHnhYmuLjPthBbnq1Q+dKs/kjIzFJcuVz2ihyp6wHgp7RYNgfNN7vTQ+bVnrrCTBmkvKveOaqBqNbWVXO/fvKBsY+oV3vMk8=
